# Generated by Django 3.1 on 2020-08-09 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=256)),
                ('event_category', models.CharField(choices=[('CONFERENCE', 'Conferencia'), ('CONGRESS', 'Congreso'), ('SEMINAR', 'Seminario'), ('COURSE', 'Curso')], max_length=20)),
                ('event_place', models.CharField(max_length=256)),
                ('event_address', models.URLField(max_length=256)),
                ('event_initial_date', models.DateTimeField()),
                ('event_final_date', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual')], max_length=20)),
                ('thumbnail', models.ImageField(upload_to='event_thumbnails/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
